config/routes.rb
Eduapp::Application.routes.draw do
  resources :pages do
    collection do
      get :bids
      get :referrals
      get :inbox
    end
  end
  
  authenticated :user do
    root :to => 'home#index'
  end

  devise_for :users, :controllers => { :registrations => "registrations"}  
  devise_scope :user do
    get "/confirm" => "registrations#confirm"
  end
  
  root :to => "home#index"
  
  resources :users
  resources :educations
  resources :experiences
  resources :public_profiles

  resources :profiles do
    collection do
      get :about
      get :commitment
      get :experience
      get :education
    end
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_filter :authenticate_user!
  def index
  end

  def commitment
  end

  def education
  #@education = current_user.educations.build
  end

  def experiences
  end

  def about
  end

  def update
    respond_to do |wants|
      if current_user.update_attributes(params[:user])
        flash[:notice] = 'User profile was successfully updated.'
        wants.html { redirect_to(profiles_path) }
        wants.xml  { head :ok }
      else
        wants.html { render :action => "edit" }
        wants.xml  { render :xml => @model.errors, :status => :unprocessable_entity }
      end
    end
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/about.html.erb
<div class="container main_container">

	<div class="row nav_back">
		<div class="span2">
			<ul class="nav nav-list">
				<li class=<%= "active" if params[:action] == "index" %>><%= link_to "Profile", profiles_path %></li>
				<li class=<%= "active" if params[:action] == "about" %>><%= link_to "About", about_profiles_path %></li>
				<li class=<%= "active" if params[:action] == "education" %>><%= link_to "Education", education_profiles_path %></li>
				<li class=<%= "active" if params[:action] == "experience" %>><%= link_to "Experience", experience_profiles_path %></li>
				<li class=<%= "active" if params[:action] == "commitment" %>><%= link_to "Commitment", commitment_profiles_path %></li>
			</ul>

		</div>
		<div class="span10 main">
			<div class="content">
				<h1>About me</h1>
				
				<%= render 'layouts/messages' %>
				
				<%= simple_form_for(current_user, :url => profile_path(current_user), :html => { :method => :put, :class => 'form-horizontal form-vertical' }) do |f| %>
				<%= f.error_notification %>
				<%= display_base_errors current_user %>

				<%= f.input :about, :class => "inline" do %>
				<%= f.input_field :about, :rows => 5  %>
				<%= content_tag :p, "This is your chance to tell your students about yourself.", :class => "help-block" %>
				<% end %>
				
				<%= f.input :philosopfy, :class => "inline" do %>
				<%= f.input_field :philosopfy, :rows => 5  %>
				<%= content_tag :p, "Give a short summary of your teaching philosopfy.", :class => "help-block" %>
				<% end %>
				
				<div class="form-actions">
					<%= f.button :submit, 'Save', :class => 'btn-submit btn' %>
				</div>

				<% end %>

			</div>

		</div>
	</div>
</div>

app/views/profiles/commitment.html.erb
<div class="container main_container">

	<div class="row nav_back">
		<div class="span2">
			<ul class="nav nav-list">
				<li class=<%= "active" if params[:action] == "index" %>><%= link_to "Profile", profiles_path %></li>
				<li class=<%= "active" if params[:action] == "about" %>><%= link_to "About", about_profiles_path %></li>
				<li class=<%= "active" if params[:action] == "education" %>><%= link_to "Education", education_profiles_path %></li>
				<li class=<%= "active" if params[:action] == "experience" %>><%= link_to "Experience", experience_profiles_path %></li>
				<li class=<%= "active" if params[:action] == "commitment" %>><%= link_to "Commitment", commitment_profiles_path %></li>
			</ul>

		</div>
		<div class="span10 main">
			<div class="content">
				<h1>About me</h1>
				<hr>
				<%= render 'layouts/messages' %>
				
				<h2>Subjects</h2>
				<h2>Location</h2>
				<h2>Arrangement</h2>

			</div>

		</div>
	</div>
</div>

app/views/profiles/education.html.erb
<div class="container main_container">

	<div class="row nav_back">
		<div class="span2">
			<ul class="nav nav-list">
				<li class=<%= "active" if params[:action] == "index" %>><%= link_to "Profile", profiles_path %></li>
				<li class=<%= "active" if params[:action] == "about" %>><%= link_to "About", about_profiles_path %></li>
				<li class=<%= "active" if params[:action] == "education" %>><%= link_to "Education", education_profiles_path %></li>
				<li class=<%= "active" if params[:action] == "experience" %>><%= link_to "Experience", experience_profiles_path %></li>
				<li class=<%= "active" if params[:action] == "commitment" %>><%= link_to "Commitment", commitment_profiles_path %></li>
			</ul>

		</div>
		<div class="span10 main">
			<div class="content">
				<h1>Education</h1>
				<hr>
				<%= render 'layouts/messages' %>
				<% current_user.educations.each do |education| %>
				<h2><%= education.title %></h2>
				<p>Period: <strong><%= education.start_year %> - <%= education.end_year %></strong></p>
				<p>Level: <strong><%= education.level %></strong></p>
				<p>Remarks: <strong><%= education.remarks %></strong></p>
				<hr>
				<% end %>

				<h2>Add education</h2>

				<%= simple_form_for(current_user.educations.build, :html => { :method => :post, :class => 'form-horizontal form-vertical' }) do |e| %>
				<%= e.error_notification %>
				<%= display_base_errors current_user %>


				<%= e.input :title, :autofocus => true, :required => true %>
				<%= e.input :start_year, :required => true %>
				<%= e.input :end_year, :required => true %>
				<%= e.input :level, :required => true %>
				<%= e.input :remarks, :input_html => { :cols => 50, :rows => 3 }  %>


				<div class="form-actions">
					<%= e.button :submit, 'Add Education', :class => 'btn-submit btn' %>
				</div>

				<% end %>

			</div>

		</div>
	</div>
</div>

app/views/profiles/experience.html.erb
<div class="container main_container">

	<div class="row nav_back">
		<div class="span2">
			<ul class="nav nav-list">
				<li class=<%= "active" if params[:action] == "index" %>><%= link_to "Profile", profiles_path %></li>
				<li class=<%= "active" if params[:action] == "about" %>><%= link_to "About", about_profiles_path %></li>
				<li class=<%= "active" if params[:action] == "education" %>><%= link_to "Education", education_profiles_path %></li>
				<li class=<%= "active" if params[:action] == "experience" %>><%= link_to "Experience", experience_profiles_path %></li>
				<li class=<%= "active" if params[:action] == "commitment" %>><%= link_to "Commitment", commitment_profiles_path %></li>
			</ul>

		</div>
		<div class="span10 main">
			<div class="content">
				<h1>Experiences</h1>
				<hr>
				<%= render 'layouts/messages' %>
				<% current_user.experiences.each do |experience| %>
				<h2><%= experience.name %></h2>
				<p>Title: <strong><%= experience.title %></strong></p>
				<p>Period: <strong><%= experience.start_year %> - <%= experience.end_year %></strong></p>
				<p>Remarks: <strong><%= experience.remarks %></strong></p>
				<hr>
				<% end %>

				<h2>Add experience</h2>
				

				<%= simple_form_for(current_user.experiences.build, :html => { :method => :post, :class => 'form-horizontal form-vertical' }) do |e| %>
				<%= e.error_notification %>
				<%= display_base_errors current_user %>


				<%= e.input :name, :autofocus => true, :required => true %>
				<%= e.input :title, :required => true %>
				<%= e.input :start_year, :required => true %>
				<%= e.input :end_year, :required => true %>
				<%= e.input :remarks, :input_html => { :cols => 50, :rows => 3 }  %>


				<div class="form-actions">
					<%= e.button :submit, 'Add experience', :class => 'btn-submit btn' %>
				</div>

				<% end %>

			</div>

		</div>
	</div>
</div>

app/views/profiles/index.html.erb
<div class="container main_container">

	<div class="row nav_back">
		<div class="span2">
			<ul class="nav nav-list">
				<li class=<%= "active" if params[:action] == "index" %>><%= link_to "Profile", profiles_path %></li>
				<li class=<%= "active" if params[:action] == "about" %>><%= link_to "About", about_profiles_path %></li>
				<li class=<%= "active" if params[:action] == "education" %>><%= link_to "Education", education_profiles_path %></li>
				<li class=<%= "active" if params[:action] == "experience" %>><%= link_to "Experience", experience_profiles_path %></li>
				<li class=<%= "active" if params[:action] == "commitment" %>><%= link_to "Commitment", commitment_profiles_path %></li>
			</ul>

		</div>
		<div class="span10 main">
			<div class="content">
				<h1>Profile</h1>
				<hr>
				<%= render 'layouts/messages' %>

				<%= simple_form_for(current_user, :url => profile_path(current_user), :html => { :method => :put, :class => 'form-horizontal form-vertical' }) do |f| %>
				<%= f.error_notification %>
				<%= display_base_errors current_user %>
				<%= f.input :name, :autofocus => true, :required => true %>
				<%= f.input :surname, :required => true %>
				<%= f.input :dob, :label => "Date of birth", include_blank: true, start_year: Date.today.year - 90, end_year: Date.today.year - 10 %>
				<%= f.input :sex, as: :select, include_blank: false,collection: [["Male", 1], ["Female",0]], :selected => current_user.sex ? 1 : 0%> 
				<%= f.input :race, placeholder: "Chinese, Malay, Indian, Other" %>
				<%= f.input :qualification, label: "Highest qualification", placeholder: "BSc, Master, PhD" %>
				<%= f.input :zip, label: "Postal code", placeholder: "Eg. 123456" %>

				<div class="form-actions">
					<%= f.button :submit, 'Save', :class => 'btn-submit btn' %>
				</div>

				<% end %>

			</div>

		</div>
	</div>
</div>